Repository algorithm-ssau/Toast-n-Honey, pull requests merged in 2020-04, with the labels that each got.

#30 Some fixes and code format
  TnH_app/__init__.py
  TnH_app/database/Toast-N-Honey.db
  TnH_app/database/db_scheme.erwin
  TnH_app/routes.py
  requirements.txt
Labels: fix

#33 TnH-17 Добавил файлы для конфигурация startup при деплое в Azure
  .deployment
  startup.py
  startup.txt
Labels: enhancement

#35 Feature/tn h 18 добавить и настроить flask assets
  TnH_app/__init__.py
  TnH_app/assets.py
  TnH_app/routes.py
  TnH_app/webapp.py
  requirements.txt
Labels: enhancement

#31 TnH-15 Create Table Options
  TnH_app/database/Toast-N-Honey.db
  TnH_app/migrations/versions/21d2ff0a8680_add_options_table.py
  TnH_app/models.py
Labels: enhancement

#37 TnH-14: Создать модель Order
  TnH_app/migrations/versions/315f0946de5b_.py
  TnH_app/models.py
Labels: enhancement

#39 Feature/tn h 13 create customers table
  TnH_app/migrations/versions/e936b401baf4_customers_table.py
  TnH_app/models.py
Labels: dependencies
